# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab075778fc0a400891f477876ee2b790c4885f4d55ae987cfe2ce429c6233521670dce99bc7a11432729748201d5271b0273df1eb3ada4c0bdc3a6bd54b5fadb

test:
  secret_key_base: c85551786eeb61985848438e20fe7ecb3f69bffdddaf7122b90d9df45b85591f88bd8d7d64bba5d9e02ed07169d1bc6011b0587a1884ccbe27a773dae57dd782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
